[project]
name = "venv-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "google-generativeai>=0.8.4",
    "openai>=1.61.1",
    "pydantic>=2.10.6",
    "pyjwt>=2.10.1",
]
